### ISSUE TITLE
trollflow2 fails with KeyError when trying to process a message

### ISSUE THREAD

**Issue by gerritholl** [pytroll/trollflow2#192]
**Describe the bug**

When a message arrives, trollflow2 fails with a KeyError.

**To Reproduce**

Start `trollflow2` with:

```bash
satpy_launcher.py -n localhost /tmp/test.yaml -c /tmp/logging.yaml
```

where `/tmp/test.yaml` is

```yaml
product_list:
  subscribe_topics:
    - /set/fci/fdss/full
  reader:
    - fci_l1c_nc
  mask_area: False
  areas:
    eurol:
      areaname: eurol
      products:
        nir08:
          productname: nir08
          formats:
            - writer: geotiff
              fname_pattern: "test.tif"

workers:
  - fun: !!python/name:trollflow2.plugins.create_scene
  - fun: !!python/name:trollflow2.plugins.load_composites
  - fun: !!python/name:trollflow2.plugins.resample
  - fun: !!python/name:trollflow2.plugins.save_datasets
```

and `/tmp/logging.yaml` is

```yaml
version: 1
disable_existing_loggers: false
formatters:
  pytroll:
    format: '[%(asctime)s %(levelname)-8s %(name)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: pytroll
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers:
    - console
```

then trigger a message for trollflow2.

**Expected behavior**

I expect that trollflow2 processes the message successfully.

**Actual results**

The subprocess crashes and nothing is processed:

```
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/opt/pytroll/pytroll_inst/mambaforge/envs/pytroll-py311/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/pytroll/pytroll_inst/mambaforge/envs/pytroll-py311/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/pytroll/pytroll_inst/mambaforge/envs/pytroll-py311/lib/python3.11/site-packages/trollflow2/logging.py", line 141, in wrapper_decorator
    setup_queued_logging(log_queue, config=log_config)
  File "/opt/pytroll/pytroll_inst/mambaforge/envs/pytroll-py311/lib/python3.11/site-packages/trollflow2/logging.py", line 121, in setup_queued_logging
    remove_handlers_from_config(config)
  File "/opt/pytroll/pytroll_inst/mambaforge/envs/pytroll-py311/lib/python3.11/site-packages/trollflow2/logging.py", line 130, in remove_handlers_from_config
    for logger in config["loggers"]:
                  ~~~~~~^^^^^^^^^^^
KeyError: 'loggers'
[2023-10-13 14:14:41,928 CRITICAL trollflow2.launcher] Process crashed with exit code 1
```

**Environment Info:**
 - OS: CentOS 7
 - Trollflow2 Version: 0.15.0
 - Satpy Version: 0.43

**Additional context**

This is probably the same at #183, but since the error message is different here, I'm reporting it seperately.

**Comment by gerritholl** [comment]
The problem was introduced in 832a11ba7e3e0a7b543e98d3f498d092111a0659 which was part of https://github.com/pytroll/trollflow2/pull/174.

The problem is avoided if I add

```
loggers:
  '':
    level: DEBUG
    handlers: [console]
```

**Comment by gerritholl** [comment]
Except that when I add that, it fails as in #183. Somehow it didn't last week, but it does today.
