### ISSUE TITLE
Valid log config fails in trollflow2

### ISSUE THREAD

**Issue by mraspaud** [pytroll/trollflow2#197]
**Describe the bug**
When using a log config without explicit `loggers` section, trollflow2 crashes.

**To Reproduce**
Use this log config
```yaml
version: 1
disable_existing_loggers: false
formatters:
  pytroll:
    datefmt: '%Y-%m-%d %H:%M:%S'
    format: '[%(levelname)s: %(asctime)s : %(name)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: pytroll
root:
  handlers:
  - console
  level: DEBUG

```

**Expected behavior**
I expect trollflow2 to work file

**Actual results**
```python
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.11/site-packages/trollflow2/logging.py", line 141, in wrapper_decorator
    setup_queued_logging(log_queue, config=log_config)
  File "/opt/conda/lib/python3.11/site-packages/trollflow2/logging.py", line 121, in setup_queued_logging
    remove_handlers_from_config(config)
  File "/opt/conda/lib/python3.11/site-packages/trollflow2/logging.py", line 130, in remove_handlers_from_config
    for logger in config["loggers"]:
                  ~~~~~~^^^^^^^^^^^
KeyError: 'loggers'
[CRITICAL: 2024-02-12 16:14:30 : trollflow2.launcher] Process crashed with exit code 1
```

**Comment by pnuu** [comment]
Duplicate of https://github.com/pytroll/trollflow2/issues/192
