### ISSUE TITLE
Failure when saving in satellite-native projection

### ISSUE THREAD

**Issue by pnuu** [pytroll/trollflow2#88]
**Describe the bug**
Processing fails when using satellite-native projection, that is `null` as projection in `trollflow.yaml`.

**To Reproduce**
Use `null` as area, like in the following stripped-down non-working product list:

```yaml
product_list:
  areas:
    null:
      areaname: geos
      products:
        airmass:
          productname: airmass

```

**Expected behavior**
The images should be saved without resampling.

**Actual results**
Process crashes with

```python
Traceback (most recent call last):
  File "/home/users/satman/current/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/users/satman/current/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/satman/current/lib/python3.8/site-packages/trollflow2/launcher.py", line 268, in process
    cwrk.pop('fun')(job, **cwrk)
  File "/home/users/satman/current/lib/python3.8/site-packages/trollflow2/plugins/__init__.py", line 136, in resample
    if not set(scn.datasets.keys()).issuperset(scn.wishlist):
AttributeError: 'Scene' object has no attribute 'datasets'
```

**Environment Info:**
 - Trollflow2 Version: 0.7.2.dev19+g4158921 (latest master)
 - Satpy Version: 0.23.0

**Comment by djhoese** [comment]
@mraspaud made `.datasets` private now so it is `._datasets`, but you should be able to do `scn.keys()` instead anyway.
